/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:31d8a769-26ed-45c1-bcda-71ca7465833e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_YD2OPi2Xt",
    "aws_user_pools_web_client_id": "3lka1j5gk4ci9viif7b7sfb59s",
    "oauth": {}
};


export default awsmobile;
