/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://5rudw7zihncd3ec3veggisktxe.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-west-1:8e0b415c-1857-4f68-a074-d843eb7d1990",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rhak8ucRL",
    "aws_user_pools_web_client_id": "2ltciek9r4j1k7hj8gsr6k80rm",
    "oauth": {},
    "aws_content_delivery_bucket": "fyp-20210407095439-hostingbucket-fyproj",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d2wclsos8gnquv.cloudfront.net"
};


export default awsmobile;
